services:
  stepca:
    image: smallstep/step-ca
    ports:
      - 9010:9000
    environment:
      - "DOCKER_STEPCA_INIT_NAME=Smallstep"
      - "DOCKER_STEPCA_INIT_DNS_NAMES=localhost,smallstep,smallstep.internal"
      - "DOCKER_STEPCA_INIT_ACME=true"
    networks:
      traefik_network:
        aliases:
          - "smallstep"
          - "smallstep.internal"
    volumes:
      - "smallstep_data:/home/step:z"
  traefik:
    image: "traefik:latest"
    # needs to be privileged to access docker socket
    privileged: true
    depends_on:
      - stepca
    command:
      - "--log=true"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_traefik_network"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.charlie.acme.email=admin"
      - "--certificatesresolvers.charlie.acme.caserver=https://smallstep:9000/acme/acme/directory"
      - "--certificatesResolvers.charlie.acme.httpChallenge=true"
      - "--certificatesResolvers.charlie.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.charlie.acme.tlsChallenge=true"
      - "--certificatesresolvers.charlie.acme.storage=acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.httpsonly.redirectscheme.scheme=https"
      - "traefik.http.middlewares.httpsonly.redirectscheme.permanent=true"
      - "traefik.http.routers.httpsonly.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.httpsonly.middlewares=httpsonly"
      - "traefik.http.routers.dashboard.rule=Host(`charlie.traefik.internal`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      #- "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`charlie.traefik.internal`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=charlie"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=charlie"
      #- "traefik.http.routers.api.tls.entrypoints=websecure"
    environment:
      LEGO_CA_CERTIFICATES: "/usr/local/share/ca-certificates/certs/root_ca.crt"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8080"
    networks:
      traefik_network:
        aliases:
          - "traefik"
          - "charlie.traefik.internal"
    volumes:
      - "/run/podman/podman.sock:/var/run/docker.sock:ro"
      - "smallstep_data:/usr/local/share/ca-certificates:ro,z"
volumes:
  smallstep_data:
    driver: local
networks:
  traefik_network:
    driver: bridge