services:
  stepca:
    image: smallstep/step-ca
    networks:
      treafik_network:
        aliases:
          - "stepca.internal"
    ports:
      - 9000:9000
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=treafik_network"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.charlie.acme.tlsChallenge=true"
      - "--certificatesResolvers.charlie.acme.email=admin"
      - "--certificatesResolvers.charlie.acme.storage=/etc/acme/acme.json"
      - "--certificatesresolvers.charlie.acme.caserver=https://smallstep.internal:9000/acme/acme/directory"
      - "--certificatesResolvers.charlie.acme.httpChallenge=true"
      - "--certificatesResolvers.charlie.acme.httpChallenge.entryPoint=web"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik0.entrypoints=web"
      - "traefik.http.routers.traefik0.rule=Host(`charlie.traefik.internal`)"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - treafik_network
networks:
  treafik_network:
    driver: bridge