services:
  stepca:
    image: smallstep/step-ca
    ports:
      - 9010:9000
    environment:
      - "DOCKER_STEPCA_INIT_NAME=Smallstep"
      - "DOCKER_STEPCA_INIT_DNS_NAMES=localhost,smallstep,smallstep.internal"
      - "DOCKER_STEPCA_INIT_ACME=true"
    networks:
      traefik_network:
        aliases:
          - "smallstep"
          - "smallstep.internal"
    dns:
      - 192.168.0.3
    volumes:
      - "smallstep_data:/home/step"
    # healthcheck: # optional: remember to adapt the host:port to your environment
    #     test: ["CMD-SHELL", "wget -q --tries=1 --no-check-certificate https://localhost:9000/health -O - | grep -Eo '\"status\"\\s*:\\s*ok' || exit 1"]
    #     interval: 60s
    #     timeout: 10s
    #     retries: 3
    #     start_period: 40s
    restart: unless-stopped
  traefik:
    image: "traefik:latest"
    # needs to be privileged to access docker socket
    privileged: true
    # depends_on:
    #   stepca:
    #     condition: service_healthy
    command:
      - "--log=true"
      - "--log.level=DEBUG"

      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_traefik_network"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.charlie.acme.email=admin"
      - "--certificatesresolvers.charlie.acme.caserver=https://smallstep:9000/acme/acme/directory"
      - "--certificatesResolvers.charlie.acme.httpChallenge=true"
      - "--certificatesResolvers.charlie.acme.httpChallenge.entryPoint=web"
      # - "--certificatesResolvers.charlie.acme.tlsChallenge=true"
      - "--certificatesresolvers.charlie.acme.storage=/traefik_data/acme.json"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.httpsonly.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.httpsonly.redirectscheme.permanent=true"
      # - "traefik.http.routers.httpsonly.rule=HostRegexp(`{any:.*}`)"
      # - "traefik.http.routers.httpsonly.middlewares=httpsonly"
      # - "traefik.http.routers.httpsonly.entrypoints=web"
      - "traefik.http.routers.dashboard.rule=Host(`charlie.traefik.internal`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.entrypoints=web,websecure"
      - "traefik.http.routers.api.rule=Host(`charlie.traefik.internal`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=charlie"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=charlie"
      - "traefik.http.routers.api.entrypoints=web,websecure"
    environment:
      LEGO_CA_CERTIFICATES: "/usr/local/share/ca-certificates/certs/root_ca.crt"
    ports:
      - "80:80"
      - "443:443"
      - "8084:8080"
    networks:
      traefik_network:
        aliases:
          - "traefik"
          - "charlie.traefik.internal"
    volumes:
      - "/run/podman/podman.sock:/var/run/docker.sock:ro"
      - "smallstep_data:/usr/local/share/ca-certificates:ro"
      - "traefik_data:/traefik_data"
    restart: unless-stopped
volumes:
  smallstep_data:
    driver: local
  traefik_data:
    driver: local
networks:
  traefik_network:
    driver: bridge