services:
  pihole:
    container_name: "pihole"
    image: pihole/pihole:latest
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: Europe/Berlin
      TEMPERATUREUNIT: c
      ServerIP: 192.168.0.3
      PIHOLE_DNS_: 8.8.8.8;8.8.4.4
      DNSSEC: true
      DHCP_ACTIVE: true
      DHCP_START: 192.168.0.10
      DHCP_END: 192.168.0.190
      DHCP_ROUTER: 192.168.0.1
      PIHOLE_DOMAIN: internal
      VIRTUAL_HOST: pihole.internal
    # Volumes store your data between container upgrades
    volumes:
      - pihole_data:/etc/pihole/
      - dnsmasq_data:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    privileged: true
    networks:
      pihole_network:
        ipv4_address: 192.168.0.3
volumes:
  pihole_data:
    driver: local
  dnsmasq_data:
    driver: local
networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: enp4s0
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          ip_range: 192.168.0.3/32
          gateway: 192.168.0.1