services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - JELLYFIN_PublishedServerUrl=https://jellyfin.internal
    volumes:
      - jellyfin_data:/config
      - /mnt/shipyard/white container:/data/white container
    networks:
      - traefik_network
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik_network"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8500"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.internal`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=bravo"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
volumes:
  jellyfin_data:
    driver: local
networks:
  traefik_network:
    external: true
    name: traefik_traefik_network