services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_traefik_network
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n.rule=Host(`n8n.internal`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=bravo
      - traefik.http.routers.n8n.entrypoints=websecure
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_PATH
      - WEBHOOK_URL=https://n8n.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - n8n_data:/home/node
    networks:
      - traefik_network
      
volumes:
  n8n_data:
    driver: local
networks:
  traefik_network:
    external: true
    name: traefik_traefik_network