services:
  ntfy:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Berlin    # optional: set desired timezone
    volumes:
      - ntfy_cache:/var/cache/ntfy:Z
    networks:
      - traefik_network
    # ports:
    #   - 8010:80
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik_network"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.internal`)"
      - "traefik.http.routers.ntfy.tls=true"
      - "traefik.http.routers.ntfy.tls.certresolver=charlie"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
volumes:
  ntfy_cache:
    driver: local
networks:
  traefik_network:
    external: true
    name: traefik_traefik_network