services:
  chown:
    image: busybox:stable-musl
    user: root
    volumes:
      - homeassistant_data:/homeassistant_data
    command: chown -R 1000:1000 /homeassistant_data
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    volumes:
        - homeassistant_data:/config
        - /etc/localtime:/etc/localtime:ro
        - /run/dbus:/run/dbus:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_traefik_network
      - traefik.http.routers.homeassistant.rule=Host(`homeassistant.internal`)
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=charlie
      - traefik.http.routers.homeassistant.entrypoints=websecure
      - traefik.http.services.homeassistant.server.port=8123
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    network_mode: host
    depends_on:
      chown:
        condition: service_completed_successfully
volumes:
  homeassistant_data:
    driver: local