services:
  traefik:
    image: "traefik:latest"
    # needs to be privileged to access docker socket
    privileged: true
    command:
      - "--log=true"
      - "--log.level=DEBUG"

      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_traefik_network"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.charlie.acme.email=admin"
      - "--certificatesresolvers.charlie.acme.caserver=https://smallstep.internal:9010/acme/acme/directory"
      - "--certificatesResolvers.charlie.acme.httpChallenge=true"
      - "--certificatesResolvers.charlie.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.charlie.acme.storage=/traefik_data/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`charlie.traefik.internal`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.entrypoints=web,websecure"
      - "traefik.http.routers.api.rule=Host(`charlie.traefik.internal`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=charlie"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=charlie"
      - "traefik.http.routers.api.entrypoints=web,websecure"
    environment:
      LEGO_CA_CERTIFICATES: "/usr/local/share/ca-certificates/certs/root_ca.crt"
    ports:
      - "80:80"
      - "443:443"
      - "8084:8080"
    networks:
      traefik_network:
        aliases:
          - "traefik"
          - "charlie.traefik.internal"
    dns:
      - 192.168.0.3
    volumes:
      - "/run/run/docker.sock:/var/run/docker.sock:ro"
      # - "smallstep_data:/usr/local/share/ca-certificates:ro"
      - "traefik_data:/traefik_data"
    restart: unless-stopped
volumes:
  traefik_data:
    driver: local
networks:
  traefik_network:
    driver: bridge