services:
  # sidecar to download ca certificate
  bootstrap:
    image: alpine:latest
    entrypoint: "/usr/bin/wget"
    command: ["--no-check-certificate", "https://smallstep.internal:9010/roots.pem", "-O", "/usr/local/share/ca-certificates/roots.pem"]
    # command: ["sleep", "infinity"]
    volumes:
      - certs_data:/usr/local/share/ca-certificates
    restart: no
  traefik:
    image: "traefik:latest"
    # depends_on:
    #   bootstrap:docker
    #     condition: service_completed_successfully
    # needs to be privileged to access docker socket
    privileged: true
    command:
      - "--log=true"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_traefik_network"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.bravo.acme.email=admin"
      - "--certificatesresolvers.bravo.acme.caserver=https://smallstep.internal:9010/acme/acme/directory"
      - "--certificatesResolvers.bravo.acme.httpChallenge=true"
      - "--certificatesResolvers.bravo.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.bravo.acme.storage=/traefik_data/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`bravo.traefik.internal`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.entrypoints=web,websecure"
      - "traefik.http.routers.api.rule=Host(`bravo.traefik.internal`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=bravo"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=bravo"
      - "traefik.http.routers.api.entrypoints=web,websecure"
    environment:
      LEGO_CA_CERTIFICATES: "/usr/local/share/ca-certificates/root.pem"
    ports:
      - "80:80"
      - "443:443"
      - "8084:8080"
    networks:
      - traefik_network
    dns:
      - 192.168.0.3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "smallstep_data:/usr/local/share/ca-certificates:ro"
      - "traefik_data:/traefik_data"
    restart: unless-stopped
volumes:
  traefik_data:
    driver: local
  certs_data:
    driver: local
networks:
  traefik_network:
    driver: bridge